### ISSUE TITLE
Mobile problem

### ISSUE THREAD

**Issue by Ninetheme** [OriginalEXE/Switcheroo#10]
Hi

Firstly thank you so much!

If customer visit themeforest via mobile device and click preview opened  "current_product" demo. 

Best Regards

**Comment by OriginalEXE** [comment]
Hello,

I'm not sure I understood what the problem is, can you please try explaining in more details? Also, a url where the problem can be seen would help.

Thanks

**Comment by Ninetheme** [comment]
Thank you and I'm sorry for english

Please visit via mobile device this url and click on "live preview" button : http://themeforest.net/item/agen-one-page-multi-page-responsive-wp-theme/11425592

Theme is agen but browser showing church theme ( current product ) 

a hug!

**Comment by OriginalEXE** [comment]
Oh, understood.

Please look into this issue, solution was provided there by the person who first found the bug:
https://github.com/OriginalEXE/Switcheroo/issues/5

Note that you will have to apply fix in the unminified version of the script, and then you can minify it yourself.

Sorry for not fixing this myself, I kinda abandoned the Switcheroo, was thinking lately about updating it.

**Comment by Ninetheme** [comment]
I have found a solution , if you need please let me know. You can delete current products codes and jquery.mobile... code
