### ISSUE TITLE
Switcheroo-inspired plugin

### ISSUE THREAD

**Issue by iamntz** [OriginalEXE/Switcheroo#8]
Hi guys, I just made this: https://github.com/iamntz/showcaser

In the readme you will find the reason I choose to rewrite instead of modify (tl;dr version is that Switcheroo has too many libs that are not really necessary)

**Comment by OriginalEXE** [comment]
Hey, looks great, very nice of you to make products config compatible! I don't have much time lately for properly maintaining this so it's nice to see someone made a step forward in the right direction.

**Comment by Misplon** [comment]
Very cool @iamntz, thanks for sharing.
